//! Basic player build placement command.

use alchimera_core::{ids::ItemId, seed::WorldSeed};
use alchimera_generation::{chunk::ChunkCoord, objects::ObjectPrototypeKey};
use bevy::prelude::{
    App, Commands, Component, Event, EventReader, Name, Plugin, ResMut, Resource, Transform, Update,
};

use crate::{harvesting::PlayerInventory, objects::WorldObject};

/// Marker for an object placed by the player rather than generated by terrain.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Component)]
pub struct PlayerBuiltObject {
    pub chunk: ChunkCoord,
}

/// Monotonic placement state used to allocate stable IDs for player-built objects.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Resource)]
pub struct BuildPlacementState {
    seed: WorldSeed,
    next_index: u64,
}

impl BuildPlacementState {
    #[must_use]
    pub const fn new(seed: WorldSeed) -> Self {
        Self {
            seed,
            next_index: 0,
        }
    }

    #[must_use]
    pub fn next_object_id_for_chunk(self, chunk: ChunkCoord) -> alchimera_core::ids::ObjectId {
        alchimera_core::ids::ObjectId::from_seed_chunk_and_index(
            self.seed,
            [chunk.x, chunk.z],
            self.next_index,
        )
    }

    fn take_next_object_id_for_chunk(
        &mut self,
        chunk: ChunkCoord,
    ) -> alchimera_core::ids::ObjectId {
        let id = self.next_object_id_for_chunk(chunk);
        self.next_index += 1;
        id
    }
}

impl Default for BuildPlacementState {
    fn default() -> Self {
        Self::new(WorldSeed::new(0))
    }
}

/// Request to place one buildable object using an inventory item.
#[derive(Debug, Clone, PartialEq, Event)]
pub struct PlaceObject {
    prototype_key: ObjectPrototypeKey,
    item_id: ItemId,
    transform: Transform,
    chunk: ChunkCoord,
}

impl PlaceObject {
    #[must_use]
    pub const fn new(
        prototype_key: ObjectPrototypeKey,
        item_id: ItemId,
        transform: Transform,
        chunk: ChunkCoord,
    ) -> Self {
        Self {
            prototype_key,
            item_id,
            transform,
            chunk,
        }
    }
}

/// Registers player build placement resources and systems.
#[derive(Debug, Default)]
pub struct BuildingPlugin;

impl Plugin for BuildingPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<PlayerInventory>()
            .init_resource::<BuildPlacementState>()
            .add_event::<PlaceObject>()
            .add_systems(Update, apply_place_object_events);
    }
}

fn apply_place_object_events(
    mut commands: Commands,
    mut events: EventReader<PlaceObject>,
    mut inventory: ResMut<PlayerInventory>,
    mut placement: ResMut<BuildPlacementState>,
) {
    for event in events.read() {
        if inventory.remove_items(&event.item_id, 1).is_err() {
            continue;
        }

        let id = placement.take_next_object_id_for_chunk(event.chunk);
        commands.spawn((
            WorldObject {
                id,
                prototype_key: event.prototype_key,
            },
            PlayerBuiltObject { chunk: event.chunk },
            Name::new(format!("placed:{}:{id}", event.prototype_key.as_str())),
            event.transform,
        ));
    }
}
